spring.application.name=credit-engine
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/credit_engine}
spring.datasource.username=${DB_USER:credit_engine}
spring.datasource.password=${DB_PASSWORD:credit_engine}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.flyway.enabled=true
server.error.include-message=never
server.error.include-stacktrace=never
credit.import.max-rows=${CSV_MAX_ROWS:100}
spring.servlet.multipart.max-file-size=256KB
spring.servlet.multipart.max-request-size=300KB
